// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | IdFormSlice
  | TextBlockSlice
  | StatementSlice
  | ApplicationFormSlice
  | CtaSlice
  | KeyFiguresSlice
  | HeroBannerSlice
  | TextSlice
  | ValuePropositionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = HeaderDocument | PageDocument;

/**
 * Item in *ApplicationForm → Default → Primary → Sessions*
 */
export interface ApplicationFormSliceDefaultPrimarySessionsItem {
  /**
   * Name field in *ApplicationForm → Default → Primary → Sessions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.sessions[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Primary content in *ApplicationForm → Default → Primary*
 */
export interface ApplicationFormSliceDefaultPrimary {
  /**
   * Title field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * First Name field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.first_name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  first_name_label: prismic.KeyTextField;

  /**
   * Last Name field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.last_name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  last_name_label: prismic.KeyTextField;

  /**
   * Gender field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.gender_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gender_label: prismic.KeyTextField;

  /**
   * Date of birth field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.date_of_birth_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_of_birth_label: prismic.KeyTextField;

  /**
   * Nationality field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.nationality_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nationality_label: prismic.KeyTextField;

  /**
   * Work phone field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.work_phone_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  work_phone_label: prismic.KeyTextField;

  /**
   * Email field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.email_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_label: prismic.KeyTextField;

  /**
   * Session field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.session_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  session_label: prismic.KeyTextField;

  /**
   * Sessions field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.sessions[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  sessions: prismic.GroupField<
    Simplify<ApplicationFormSliceDefaultPrimarySessionsItem>
  >;

  /**
   * Submit button field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.submit_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_label: prismic.KeyTextField;

  /**
   * Privacy field in *ApplicationForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: application_form.default.primary.privacy_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  privacy_text: prismic.RichTextField;
}

/**
 * Default variation for ApplicationForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ApplicationFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ApplicationFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ApplicationForm*
 */
type ApplicationFormSliceVariation = ApplicationFormSliceDefault;

/**
 * ApplicationForm Shared Slice
 *
 * - **API ID**: `application_form`
 * - **Description**: ApplicationForm
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ApplicationFormSlice = prismic.SharedSlice<
  "application_form",
  ApplicationFormSliceVariation
>;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Title field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Link field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Primary content in *HeroBanner → Image → Primary*
 */
export interface HeroBannerSliceImagePrimary {
  /**
   * Image field in *HeroBanner → Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.image.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image variation for HeroBanner Slice
 *
 * - **API ID**: `image`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSliceImage = prismic.SharedSliceVariation<
  "image",
  Simplify<HeroBannerSliceImagePrimary>,
  never
>;

/**
 * Primary content in *HeroBanner → Video → Primary*
 */
export interface HeroBannerSliceVideoPrimary {
  /**
   * Video field in *HeroBanner → Video → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.video.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Video variation for HeroBanner Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSliceVideo = prismic.SharedSliceVariation<
  "video",
  Simplify<HeroBannerSliceVideoPrimary>,
  never
>;

/**
 * Primary content in *HeroBanner → Image with text → Primary*
 */
export interface HeroBannerSliceImageWithTextPrimary {
  /**
   * Background Image field in *HeroBanner → Image with text → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.imageWithText.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Title field in *HeroBanner → Image with text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.imageWithText.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *HeroBanner → Image with text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.imageWithText.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Image with text variation for HeroBanner Slice
 *
 * - **API ID**: `imageWithText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSliceImageWithText = prismic.SharedSliceVariation<
  "imageWithText",
  Simplify<HeroBannerSliceImageWithTextPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation =
  | HeroBannerSliceImage
  | HeroBannerSliceVideo
  | HeroBannerSliceImageWithText;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Primary content in *IdForm → Default → Primary*
 */
export interface IdFormSliceDefaultPrimary {
  /**
   * Title field in *IdForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: id_form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *IdForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: id_form.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Form Id field in *IdForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: id_form.default.primary.form_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  form_id: prismic.KeyTextField;

  /**
   * Privacy field in *IdForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: id_form.default.primary.privacy_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  privacy_text: prismic.RichTextField;
}

/**
 * Default variation for IdForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IdFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IdFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IdForm*
 */
type IdFormSliceVariation = IdFormSliceDefault;

/**
 * IdForm Shared Slice
 *
 * - **API ID**: `id_form`
 * - **Description**: IdForm
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IdFormSlice = prismic.SharedSlice<"id_form", IdFormSliceVariation>;

/**
 * Item in *KeyFigures → Default → Primary → Items*
 */
export interface KeyFiguresSliceDefaultPrimaryItemsItem {
  /**
   * Value field in *KeyFigures → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_figures.default.primary.items[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;

  /**
   * Label field in *KeyFigures → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_figures.default.primary.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *KeyFigures → Default → Primary*
 */
export interface KeyFiguresSliceDefaultPrimary {
  /**
   * Eyebrow field in *KeyFigures → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_figures.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *KeyFigures → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_figures.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Items field in *KeyFigures → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: key_figures.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<KeyFiguresSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for KeyFigures Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type KeyFiguresSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<KeyFiguresSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *KeyFigures*
 */
type KeyFiguresSliceVariation = KeyFiguresSliceDefault;

/**
 * KeyFigures Shared Slice
 *
 * - **API ID**: `key_figures`
 * - **Description**: KeyFigures
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type KeyFiguresSlice = prismic.SharedSlice<
  "key_figures",
  KeyFiguresSliceVariation
>;

/**
 * Primary content in *Statement → Default → Primary*
 */
export interface StatementSliceDefaultPrimary {
  /**
   * Eyebrow field in *Statement → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Statement → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statement.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for Statement Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatementSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatementSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Statement*
 */
type StatementSliceVariation = StatementSliceDefault;

/**
 * Statement Shared Slice
 *
 * - **API ID**: `statement`
 * - **Description**: Statement
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatementSlice = prismic.SharedSlice<
  "statement",
  StatementSliceVariation
>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Title field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Content field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

/**
 * Item in *ValueProposition → Default → Primary → Items*
 */
export interface ValuePropositionSliceDefaultPrimaryItemsItem {
  /**
   * Icon field in *ValueProposition → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *ValueProposition → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ValueProposition → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *ValueProposition → Default → Primary*
 */
export interface ValuePropositionSliceDefaultPrimary {
  /**
   * Title field in *ValueProposition → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Items field in *ValueProposition → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: value_proposition.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<ValuePropositionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for ValueProposition Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuePropositionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ValuePropositionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ValueProposition*
 */
type ValuePropositionSliceVariation = ValuePropositionSliceDefault;

/**
 * ValueProposition Shared Slice
 *
 * - **API ID**: `value_proposition`
 * - **Description**: ValueProposition
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuePropositionSlice = prismic.SharedSlice<
  "value_proposition",
  ValuePropositionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HeaderDocument,
      HeaderDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ApplicationFormSlice,
      ApplicationFormSliceDefaultPrimarySessionsItem,
      ApplicationFormSliceDefaultPrimary,
      ApplicationFormSliceVariation,
      ApplicationFormSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceImagePrimary,
      HeroBannerSliceVideoPrimary,
      HeroBannerSliceImageWithTextPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceImage,
      HeroBannerSliceVideo,
      HeroBannerSliceImageWithText,
      IdFormSlice,
      IdFormSliceDefaultPrimary,
      IdFormSliceVariation,
      IdFormSliceDefault,
      KeyFiguresSlice,
      KeyFiguresSliceDefaultPrimaryItemsItem,
      KeyFiguresSliceDefaultPrimary,
      KeyFiguresSliceVariation,
      KeyFiguresSliceDefault,
      StatementSlice,
      StatementSliceDefaultPrimary,
      StatementSliceVariation,
      StatementSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      ValuePropositionSlice,
      ValuePropositionSliceDefaultPrimaryItemsItem,
      ValuePropositionSliceDefaultPrimary,
      ValuePropositionSliceVariation,
      ValuePropositionSliceDefault,
    };
  }
}
